apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginxpod
        image: nginx:1.19.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "20m"
